### ISSUE TITLE
Person name and number is not visible

### ISSUE THREAD

**Issue by ghost** [PatrickAlphaC/simple_storage#4]

**Comment by ezeamaka2** [comment]
can you copy and paste the code here?

**Comment by yash0903** [comment]
// SPDX-License-Identifier: MIT
pragma solidity 0.8.11;

contract SimpleStorage {


    People[] public people;
    struct People {
        uint256 favoriteNumber;
        string name;
    }


    function addPerson(string memory name, uint256 favoriteNumber) public {
        people.push(People(favoriteNumber, name));
    }
}

**Comment by yash0903** [comment]
The error i am getting is,  call to SimpleStorage.people errored: Error encoding arguments: Error: invalid BigNumber string (argument="value" value="" code=INVALID_ARGUMENT version=bignumber/5.5.0)
