### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Abtcapitals** [PatrickAlphaC/simple_storage#6]
![image](https://user-images.githubusercontent.com/90463193/224202571-f1dbbab4-e736-4447-b1bf-586275f6a222.png)

I ran same code as in the tutorial but was getting compilation error,
help point out the errors.

**Comment by NotZayne** [comment]
Hi when Defining people, i had the same issue. The solution is to define the struct people with a capital p st. People. and the same thing for People[] (Capital P). Then have public people just the same. Hope this helps i will be attaching my screenshot.

RED is for Caps
Purple for No Caps
![Screenshot 2023-03-12 164717](https://user-images.githubusercontent.com/126067999/224555973-5f3367ea-3b3a-499b-809f-7bd6fa54423e.png)

**Comment by Abtcapitals** [comment]
Thanks
This helps a lot sir/ma.
